# Generated by Django 4.2 on 2025-04-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Médico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('CAR', 'CARDIOLOGISTA'), ('CIR', 'CIRURGIÃO'), ('CLI', 'CLÍNICO'), ('ENDO', 'ENDOCRINOLOGISTA'), ('GE', 'GERIATRA')], max_length=4)),
                ('crm', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGEN', 'Agendado'), ('REA', 'Realizado'), ('CAN', 'Cancelado')], max_length=4)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.médico')),
            ],
            options={
                'verbose_name_plural': 'Consulta',
            },
        ),
    ]
